local DM=HCDangerMap
DM.PROTOCOL="HCS1";DM.CHANNEL="HCSafety";DM.MAX_MESSAGE=240;DM.SEND_DELAY=1.25
local function Split(v,d)local t={};local x;for x in string.gfind((v or"")..d,"(.-)"..d)do table.insert(t,x)end;return t end
function DM:Escape(v)v=tostring(v or"");v=string.gsub(v,"%%","%%25");v=string.gsub(v,"|","%%7C");v=string.gsub(v,"~","%%7E");v=string.gsub(v,"\r","%%0D");v=string.gsub(v,"\n","%%0A");return v end
function DM:Unescape(v)v=tostring(v or"");v=string.gsub(v,"%%0A"," ");v=string.gsub(v,"%%0D"," ");v=string.gsub(v,"%%7E","~");v=string.gsub(v,"%%7C","|");v=string.gsub(v,"%%25","%%");return v end
function DM:InitializeNetwork()self.Network={state="OFFLINE",queue={},seen={},receive={},counter=0,lastSend=0,nextClean=GetTime()+10}end
function DM:HideChannel()local i;for i=1,7 do local f=getglobal("ChatFrame"..i);if f and ChatFrame_RemoveChannel then ChatFrame_RemoveChannel(f,self.CHANNEL)end end end
function DM:NetworkStatus()if not self.DB or not self.DB.settings.communitySync then return"Community sync: OFF"end;local s=self.Network and self.Network.state or"OFFLINE";if s=="ONLINE"then return"Community sync: HCSafety joined"elseif s=="JOINING"then return"Community sync: joining"elseif s=="ERROR"then return"Community sync: unavailable"end;return"Community sync: offline"end
function DM:JoinNetwork()if not self.DB.settings.communitySync then return end;local id=GetChannelName(self.CHANNEL);if id and id>0 then self.Network.state="ONLINE";self:HideChannel();return end;self.Network.state="JOINING";JoinChannelByName(self.CHANNEL,nil,DEFAULT_CHAT_FRAME:GetID());if self.RefreshUI then self:RefreshUI()end end
function DM:StopNetwork()self.Network.queue={};self.Network.state="OFFLINE";if LeaveChannelByName then LeaveChannelByName(self.CHANNEL)end;if self.RefreshUI then self:RefreshUI()end end
function DM:MakeMessageId()self.Network.counter=self.Network.counter+1;local n=string.gsub(UnitName("player")or"p","[^%w]","");return string.sub(n,1,10).."-"..tostring(math.floor(GetTime())).."-"..tostring(self.Network.counter)end
function DM:Queue(typeName,payload)local id=self:MakeMessageId();local msg=self.PROTOCOL.."|"..self.MODULE.."|"..typeName.."|"..id.."|"..payload;if string.len(msg)>self.MAX_MESSAGE then self:Print("marker note is too long for the 240-byte network limit.");return nil end;if table.getn(self.Network.queue)>=30 then return nil end;table.insert(self.Network.queue,msg);return 1 end
function DM:BroadcastMarker(m)
 if not self.DB.settings.communitySync then self:Print("marker remains local because community sync is OFF.");return nil end
 local age=self:Now()-(m.lastSeen or self:Now());if age<0 then age=0 end;if age>2592000 then age=2592000 end;local payload=tostring(age).."~"..self:Escape(m.zone).."~"..self:Escape(m.subzone).."~"..(m.x and tostring(m.x)or"").."~"..(m.y and tostring(m.y)or"").."~"..self:Escape(m.dangerType).."~"..tostring(m.levelLow or 0).."~"..tostring(m.levelHigh or 0).."~"..self:Escape(self:Trim(m.note,70)).."~"..tostring(m.observations or 1)
 local ok=self:Queue("OBS",payload);if ok then self:Print("an anonymous coarse marker was queued for community sync.")end;return ok
end
function DM:AllowedSender(sender)sender=self:Trim(string.lower(sender or""),64);if sender==""then return nil end;local now=GetTime();local r=self.Network.receive[sender];if not r or now-r.started>10 then r={started=now,count=0};self.Network.receive[sender]=r end;r.count=r.count+1;if r.count>12 then return nil end;return 1 end
function DM:HandleMessage(message,sender)
 if type(message)~="string"or string.len(message)>self.MAX_MESSAGE then return end;local p=Split(message,"|");if p[1]~=self.PROTOCOL or p[2]~=self.MODULE or p[3]~="OBS"then return end;local id=p[4];if not id or string.len(id)>48 or string.find(id,"[^%w%-%_]")or self.Network.seen[id]or not self:AllowedSender(sender)then return end;self.Network.seen[id]=GetTime();local f=Split(p[5]or"","~");local age=tonumber(f[1]);local zone=self:Trim(self:Unescape(f[2]),64);local x=tonumber(f[4]);local y=tonumber(f[5]);local kind=self:ValidateType(self:Trim(self:Unescape(f[6]),32));local low=tonumber(f[7]);local high=tonumber(f[8]);local obs=tonumber(f[10])or 1
 if not age or age<0 or age>2592000 or zone==""or not kind or not low or low<0 or low>255 or not high or high<low or high>255 then return end;if(x and(x<=0 or x>1))or(y and(y<=0 or y>1))or((x and not y)or(y and not x))then x=nil;y=nil end;if obs<1 then obs=1 end;if obs>20 then obs=20 end
 local marker=self:AggregateMarker({zone=zone,subzone=self:Trim(self:Unescape(f[3]),64),x=x,y=y,dangerType=kind,levelLow=low,levelHigh=high,note=self:Trim(self:Unescape(f[9]),70),timestamp=self:Now()-age},"community");if marker and obs>1 then marker.observations=marker.observations+obs-1 end;self.Network.state="ONLINE"
end
function DM:NetworkChat(message,sender,channelName)if not self.DB.settings.communitySync then return end;if channelName and channelName~=""and string.upper(channelName)~=string.upper(self.CHANNEL)then return end;self:HandleMessage(message,sender)end
function DM:NetworkNotice(kind,channelName)if channelName and string.upper(channelName)==string.upper(self.CHANNEL)then if kind=="YOU_JOINED"then self.Network.state="ONLINE";self:HideChannel()elseif kind=="YOU_LEFT"then self.Network.state="ERROR"end;if self.RefreshUI then self:RefreshUI()end end end
function DM:NetworkUpdate()if not self.Network then return end;local now=GetTime();if self.DB.settings.communitySync and table.getn(self.Network.queue)>0 and now-self.Network.lastSend>=self.SEND_DELAY then local id=GetChannelName(self.CHANNEL);if id and id>0 then local msg=self.Network.queue[1];table.remove(self.Network.queue,1);SendChatMessage(msg,"CHANNEL",nil,id);self.Network.lastSend=now;self.Network.state="ONLINE"elseif self.Network.state~="JOINING"then self:JoinNetwork()end end;if now>=self.Network.nextClean then self.Network.nextClean=now+10;local id,at;for id,at in pairs(self.Network.seen)do if now-at>600 then self.Network.seen[id]=nil end end;self:PruneMarkers()end end
