local DM=HCDangerMap
DM.Frames={};DM.Frames.mapWidth=430;DM.Frames.mapHeight=286
local BACKDROP={bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",tile=1,tileSize=32,edgeSize=32,insets={left=10,right=10,top=10,bottom=10}}
local PANEL={bgFile="Interface\\Tooltips\\UI-Tooltip-Background",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",tile=1,tileSize=16,edgeSize=14,insets={left=3,right=3,top=3,bottom=3}}
local function Text(p,v,font,r,g,b)local f=p:CreateFontString(nil,"OVERLAY",font or"GameFontHighlightSmall");f:SetText(v or"");if r then f:SetTextColor(r,g,b)end;return f end
local function Button(p,v,w)local b=CreateFrame("Button",nil,p,"UIPanelButtonTemplate");b:SetWidth(w or 90);b:SetHeight(23);b:SetText(v);return b end
function DM:SetMinimapAngle(a)if self.Frames.minimap then self.Frames.minimap:ClearAllPoints();self.Frames.minimap:SetPoint("CENTER",Minimap,"CENTER",math.cos(a or-.6)*80,math.sin(a or-.6)*80)end end
function DM:CreateMinimapButton()local b=CreateFrame("Button","HCDangerMapMinimapButton",Minimap);b:SetWidth(31);b:SetHeight(31);b:SetFrameStrata("MEDIUM");b:SetFrameLevel(Minimap:GetFrameLevel()+8);local bg=b:CreateTexture(nil,"BACKGROUND");bg:SetTexture("Interface\\Minimap\\UI-Minimap-Background");bg:SetWidth(24);bg:SetHeight(24);bg:SetPoint("CENTER");local i=b:CreateTexture(nil,"ARTWORK");i:SetTexture("Interface\\Icons\\INV_Misc_Map_01");i:SetWidth(20);i:SetHeight(20);i:SetPoint("CENTER");local bo=b:CreateTexture(nil,"OVERLAY");bo:SetTexture("Interface\\Minimap\\MiniMap-TrackingBorder");bo:SetWidth(52);bo:SetHeight(52);bo:SetPoint("CENTER",b,"CENTER",10,-9);b:RegisterForDrag("LeftButton");b:SetScript("OnClick",function()DM:Toggle()end);b:SetScript("OnDragStart",function()this.dragging=1 end);b:SetScript("OnDragStop",function()this.dragging=nil end);b:SetScript("OnUpdate",function()if this.dragging then local s=Minimap:GetEffectiveScale();local x,y=GetCursorPosition();x=x/s;y=y/s;local cx,cy=Minimap:GetCenter();DM.DB.settings.minimapAngle=math.atan2(y-cy,x-cx);DM:SetMinimapAngle(DM.DB.settings.minimapAngle)end end);self.Frames.minimap=b end
function DM:CreateUI()
 local f=CreateFrame("Frame","HCDangerMapFrame",UIParent);f:SetWidth(920);f:SetHeight(540);f:SetFrameStrata("DIALOG");f:SetMovable(1);f:EnableMouse(1);f:SetBackdrop(BACKDROP);f:RegisterForDrag("LeftButton");f:SetScript("OnDragStart",function()this:StartMoving()end);f:SetScript("OnDragStop",function()this:StopMovingOrSizing();DM:SavePosition(this)end);local t=Text(f,self.COLORED_NAME,"GameFontNormalLarge");t:SetPoint("TOP",f,"TOP",0,-17);local st=Text(f,"Local + optional anonymous community observations  |  v"..self.VERSION,"GameFontDisableSmall",.62,.58,.5);st:SetPoint("TOP",t,"BOTTOM",0,-2);local c=Button(f,"X",28);c:SetPoint("TOPRIGHT",f,"TOPRIGHT",-14,-13);c:SetScript("OnClick",function()DM:Close()end)
 f.sync=Button(f,"Sync OFF",90);f.sync:SetPoint("TOPLEFT",f,"TOPLEFT",22,-62);f.sync:SetScript("OnClick",function()DM.DB.settings.communitySync=not DM.DB.settings.communitySync;if DM.DB.settings.communitySync then DM:JoinNetwork()else DM:StopNetwork()end;DM:RefreshUI()end);f.filter=Button(f,"Current zone",104);f.filter:SetPoint("LEFT",f.sync,"RIGHT",7,0);f.filter:SetScript("OnClick",function()DM.State.currentOnly=not DM.State.currentOnly;DM.State.offset=0;DM:RefreshUI()end);f.status=Text(f,"",nil,.88,.72,.3);f.status:SetPoint("LEFT",f.filter,"RIGHT",12,0);f.status:SetWidth(650);f.status:SetJustifyH("LEFT")
 local canvas=CreateFrame("Frame",nil,f);canvas:SetWidth(self.Frames.mapWidth);canvas:SetHeight(self.Frames.mapHeight);canvas:SetPoint("TOPLEFT",f,"TOPLEFT",22,-103);canvas:SetBackdrop(PANEL);canvas:SetBackdropColor(.025,.035,.025,.97);canvas:SetBackdropBorderColor(.43,.34,.16,1);self.Frames.mapCanvas=canvas
 local grid;for grid=1,3 do local v=canvas:CreateTexture(nil,"BACKGROUND");v:SetTexture(.28,.24,.14,.35);v:SetWidth(1);v:SetHeight(self.Frames.mapHeight-8);v:SetPoint("TOPLEFT",canvas,"TOPLEFT",grid*(self.Frames.mapWidth/4),-4);local h=canvas:CreateTexture(nil,"BACKGROUND");h:SetTexture(.28,.24,.14,.35);h:SetHeight(1);h:SetWidth(self.Frames.mapWidth-8);h:SetPoint("TOPLEFT",canvas,"TOPLEFT",4,-grid*(self.Frames.mapHeight/4))end
 self.Frames.mapPins={};local n;for n=1,20 do local p=CreateFrame("Button",nil,canvas);p:SetWidth(14);p:SetHeight(14);local dot=p:CreateTexture(nil,"ARTWORK");dot:SetTexture("Interface\\Buttons\\WHITE8X8");dot:SetWidth(9);dot:SetHeight(9);dot:SetPoint("CENTER");p.dot=dot;p:SetScript("OnClick",function()if this.marker then DM.State.selectedId=this.marker.id;DM:RefreshUI()end end);p:SetScript("OnEnter",function()if this.marker then GameTooltip:SetOwner(this,"ANCHOR_RIGHT");GameTooltip:SetText(this.marker.dangerType);GameTooltip:AddLine(this.marker.note or"",1,1,1,1);GameTooltip:Show()end end);p:SetScript("OnLeave",function()GameTooltip:Hide()end);p:Hide();self.Frames.mapPins[n]=p end
 self.Frames.mapCaption=Text(f,"","GameFontDisableSmall",.62,.59,.52);self.Frames.mapCaption:SetPoint("TOPLEFT",canvas,"BOTTOMLEFT",2,-6);self.Frames.mapCaption:SetWidth(self.Frames.mapWidth);self.Frames.mapCaption:SetJustifyH("LEFT")
 local listHead=Text(f,"MARKERS / BEACONS","GameFontNormal",1,.82,.2);listHead:SetPoint("TOPLEFT",f,"TOPLEFT",474,-103);local newer=Button(f,"Newer",60);newer:SetPoint("TOPRIGHT",f,"TOPRIGHT",-90,-95);newer:SetScript("OnClick",function()DM.State.offset=DM.State.offset-9;if DM.State.offset<0 then DM.State.offset=0 end;DM:RefreshUI()end);local older=Button(f,"Older",60);older:SetPoint("LEFT",newer,"RIGHT",5,0);older:SetScript("OnClick",function()DM.State.offset=DM.State.offset+9;DM:RefreshUI()end);f.rows={};for n=1,9 do local r=CreateFrame("Button",nil,f);r:SetWidth(420);r:SetHeight(32);r:SetPoint("TOPLEFT",f,"TOPLEFT",472,-126-((n-1)*34));r:SetBackdrop(PANEL);r:SetBackdropColor(math.mod(n,2)==0 and .05 or .025,.025,.02,.78);r.text=Text(r,"");r.text:SetPoint("LEFT",r,"LEFT",7,0);r.text:SetWidth(404);r.text:SetJustifyH("LEFT");r:SetScript("OnClick",function()if this.markerId then DM.State.selectedId=this.markerId;DM:RefreshUI()end end);f.rows[n]=r end
 f.type=Button(f,"Type: Elite",174);f.type:SetPoint("BOTTOMLEFT",f,"BOTTOMLEFT",22,18);f.type:SetScript("OnClick",function()DM.State.typeIndex=DM.State.typeIndex+1;if DM.State.typeIndex>table.getn(DM.MarkerTypes)then DM.State.typeIndex=1 end;this:SetText("Type: "..DM.MarkerTypes[DM.State.typeIndex])end);f.note=CreateFrame("EditBox",nil,f,"InputBoxTemplate");f.note:SetWidth(270);f.note:SetHeight(24);f.note:SetPoint("LEFT",f.type,"RIGHT",8,0);f.note:SetAutoFocus(nil);f.note:SetMaxLetters(100);f.note:SetScript("OnEscapePressed",function()this:ClearFocus()end);local add=Button(f,"Add local",78);add:SetPoint("LEFT",f.note,"RIGHT",7,0);add:SetScript("OnClick",function()DM:AddManual(DM.MarkerTypes[DM.State.typeIndex],f.note:GetText(),nil);f.note:SetText("")end);local addShare=Button(f,"Add + share",92);addShare:SetPoint("LEFT",add,"RIGHT",6,0);addShare:SetScript("OnClick",function()DM:AddManual(DM.MarkerTypes[DM.State.typeIndex],f.note:GetText(),1);f.note:SetText("")end);local share=Button(f,"Share selected",105);share:SetPoint("LEFT",addShare,"RIGHT",6,0);share:SetScript("OnClick",function()DM:ShareSelected()end);f.detail=Text(f,"","GameFontDisableSmall",.64,.61,.55);f.detail:SetPoint("BOTTOMLEFT",f,"BOTTOMLEFT",24,50);f.detail:SetWidth(860);f.detail:SetJustifyH("LEFT")
 self.Frames.main=f;table.insert(UISpecialFrames,"HCDangerMapFrame");f:Hide();self:CreateMinimapButton()
end
function DM:RestoreUISettings()if not self.DB then return end;local p=self.DB.settings.position;self.Frames.main:ClearAllPoints();self.Frames.main:SetPoint(p.point or"CENTER",UIParent,p.relPoint or"CENTER",p.x or 0,p.y or 0);self:SetMinimapAngle(self.DB.settings.minimapAngle);if self.DB.settings.minimap then self.Frames.minimap:Show()else self.Frames.minimap:Hide()end;self:RefreshUI()end
function DM:RefreshUI()
 if not self.DB then return end;local f=self.Frames.main;f.sync:SetText(self.DB.settings.communitySync and"Sync ON"or"Sync OFF");f.filter:SetText(self.State.currentOnly and"Current zone"or"All zones");f.status:SetText(self:NetworkStatus());local list=self:GetVisibleMarkers();local total=table.getn(list);local max=total-9;if max<0 then max=0 end;if self.State.offset>max then self.State.offset=max end;local selected=nil;local i;for i=1,9 do local m=list[self.State.offset+i];local r=f.rows[i];if m then r.markerId=m.id;local conf=m.confidence or self:GetConfidence(m);local coords=m.x and(" "..math.floor(m.x*100)..","..math.floor(m.y*100))or" zone-only";r.text:SetText(m.dangerType.." | "..m.zone..coords.." | L"..tostring(m.levelLow or 0)..(m.levelHigh and m.levelHigh~=m.levelLow and("-"..m.levelHigh)or"").." | "..tostring(m.observations or 1).." obs / "..conf.."% | "..(m.note or""));if m.id==self.State.selectedId then selected=m;r:SetBackdropBorderColor(1,.65,.15,1)else r:SetBackdropBorderColor(.25,.22,.17,1)end;r:Show()else r.markerId=nil;r:Hide()end end
 if not selected then for i=1,total do if list[i].id==self.State.selectedId then selected=list[i]end end end;if selected then f.detail:SetText("Selected "..selected.dangerType.." in "..selected.zone.."; source "..(selected.transient and"active Rescue Beacon"or"aggregated local/community data").."; last seen "..tostring(math.floor((self:Now()-(selected.lastSeen or self:Now()))/60)).."m ago.")else f.detail:SetText(total.." visible marker(s). Old observations lose confidence and expire after 30-90 days.")end;self:RefreshMapPins()
end
function DM:Open()self:ImportJournal();self:RefreshUI();self.Frames.main:Show()end;function DM:Close()self.Frames.main:Hide()end;function DM:Toggle()if self.Frames.main:IsShown()then self:Close()else self:Open()end end
DM:CreateUI()
SLASH_HCDANGERMAP1="/hcdm";SLASH_HCDANGERMAP2="/hcdangermap"
SlashCmdList["HCDANGERMAP"]=function(message)local cmd=string.lower(DM:Trim(message or"",60));if cmd=="sync on"then DM.DB.settings.communitySync=1;DM:JoinNetwork()elseif cmd=="sync off"then DM.DB.settings.communitySync=nil;DM:StopNetwork()elseif cmd=="minimap"then DM.DB.settings.minimap=not DM.DB.settings.minimap;DM:RestoreUISettings()else DM:Toggle()end;if DM.RefreshUI then DM:RefreshUI()end end
local ev=CreateFrame("Frame",nil,UIParent);local names={"VARIABLES_LOADED","PLAYER_ENTERING_WORLD","ZONE_CHANGED_NEW_AREA","ZONE_CHANGED","CHAT_MSG_SYSTEM","CHAT_MSG_HARDCORE","CHAT_MSG_CHANNEL","CHAT_MSG_CHANNEL_NOTICE"};local i;for i=1,table.getn(names)do ev:RegisterEvent(names[i])end;ev:SetScript("OnEvent",function()DM:OnEvent(event,arg1,arg2,arg9)end);ev:SetScript("OnUpdate",function()DM:NetworkUpdate()end)
